### ISSUE TITLE
When logging in to send a verification code, a redundant endpoint was requested.

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#10]
When the login prompt requires sending a verification code, there is no need to request this endpoint “account/check-phone-number” before sending the verification code.

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/8643343a-1ed3-46e8-bf88-8efcc6d09461)
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/39fc4a9e-4b81-4907-9f23-7b222f3c2490)

**Comment by Vincenzo-Wang** [comment]
The same is true for email login. There is no need to request this endpint "account/check-email" again.
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/d5e843eb-727f-4298-9bbe-03067cb83359)

**Comment by stanley355** [comment]
@Vincenzo-Wang this is not redundant, we need to check whether user require otp or not, if not required, user can directly login without OTP. You can confirm this with Hammer
