### ISSUE TITLE
Uploading KTP and passport, displaying issues with the copy and top progress bar on the third page

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#101]
<img width="462" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/eacfffd6-e6d7-4cdc-b925-4a9cd086111d">
design drawing
<img width="269" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/3b5be9fb-c471-4b0c-a17a-81692a53e29f">

**Comment by stanley355** [comment]
`Continuing` is the right grammar

**Comment by stanley355** [comment]
I will fix the progress bar
