### ISSUE TITLE
The design diagram of the login page shows the style of a page, while the current implementation is a pop-up style

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#107]
<img width="375" alt="E2AA8DFCEF23D3AB996A5889DF7DBACE" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/dbb0a358-f81c-4256-91fc-e1e54724a006">
design drawing
<img width="253" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/0d12323f-5e9a-4d09-81b6-7235b33a38f4">

**Comment by MN3280** [comment]
kindly confirm it to daisy for this issue because both iOS and android are using drawer.

**Comment by wanghuijiao** [comment]
> kindly confirm it to daisy for this issue because both iOS and android are using drawer.

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/138777f8-fdb9-4163-9436-d114a6626f45)
But the login pages for Android and iOS look different
