### ISSUE TITLE
The display image before login is partially obscured from top to bottom

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#108]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/4122074f-b624-4692-8c5f-004e2c050189
design drawing

<img width="808" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/5a9e39bd-9aee-4ea4-bf88-6d1cccfd5a69">

**Comment by MN3280** [comment]
it's because the display of the device that you're using for testing  is different from other iPhone device, that's why it was cropped, it was normal at our testing device
