### ISSUE TITLE
The refund details page shows that the amount sent is not displayed correctly and should be the same as the total displayed below

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#112]
<img width="444" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/c29ea3f2-2cd9-4f73-93c5-bf7562934076">

**Comment by MN3280** [comment]
The amount above is the amount money that you have been sent. And the amount below is the amount money that you send + the admin fee so it shouldn't be diplayed the same.

**Comment by rayhanmhd123** [comment]
i will close the issue

**Comment by lavenderh** [comment]
pass
