### ISSUE TITLE
Transaction details page, incorrect transaction time taken

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#118]
<img width="434" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/3dc1e64c-0f24-4232-a91e-3fef7934a2e2">
There may be some other fields with incorrect values on this specific page, and Hammer will communicate with you

**Comment by rayhanmhd123** [comment]
What's the issue ?

**Comment by wanghuijiao** [comment]
> What's the issue ?

You can communicate with Hammer about it

**Comment by stanley355** [comment]
Check `transfer_time`
