### ISSUE TITLE
Uploading KTP and passport, displaying issues with the copy and top progress bar on the third page（Uploading KTP and passport, displaying issues with the copy and top progress bar on the third page

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#121]
**This issue is raised again**

<img width="453" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/5627af6a-303f-4b2a-8497-2f24f437f05e">

**Comment by stanley355** [comment]
https://github.com/orgs/AyoEasy/projects/3/views/1?pane=issue&itemId=46855134

**Comment by stanley355** [comment]
@lavenderh `Continuing` is the right grammar

**Comment by stanley355** [comment]
I will check the progress bar issue
