### ISSUE TITLE
For unverified users, the bank account and payee list will be grayed out.

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#125]
<img width="527" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/0d8ce620-748d-4da3-b13b-08fe183fcd4d">

**Comment by MN3280** [comment]
![Image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/127370431/2b77e746-634e-4e3b-a128-c76a683a4458)

According to the figma design, it's not grayed out. When the user is not verified and want to open the bank acc and payee list it will show the verification drawer

**Comment by stanley355** [comment]
Gray `Bank Account` and `Recipient List`
