### ISSUE TITLE
There is no limit to continuous clicks on related button clicks, resulting in the following effects:

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#130]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/2812fdb4-3c97-46e9-9f40-b3959965b1d3

**Comment by stanley355** [comment]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/53996155/e866fe76-5427-408b-b502-057d95206d01

Is it still happening? @lavenderh

**Comment by lavenderh** [comment]
> RPReplay_Final1702360829.MP4 
> Is it still happening? @lavenderh

Yes, it still exists. I understand it is related to the network request speed, but if the interface request does not return, clicks should be restricted.

**Comment by stanley355** [comment]
Let me check
