### ISSUE TITLE
After OCR verification fails, the expiration time and nationality fields of the form should not be backfilled.

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#135]
<img width="553" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/5ed6eff7-316b-47ab-baf2-80c607b30bb0">

**Comment by stanley355** [comment]
@lavenderh for KTP, the nationality is always Indonesia, and Indonesian KTP sometime has no expiry date

**Comment by lavenderh** [comment]
> @lavenderh for KTP, the nationality is always Indonesia, and Indonesian KTP sometime has no expiry date

According to Android interaction, because ktp verification fails, the default value should not be given

**Comment by stanley355** [comment]
KTP nationality is always Indonesian because KTP only exists for Indonesian
