### ISSUE TITLE
Place of birth should be in the form of a drop-down option

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#137]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/ce2746df-e1e3-4ebf-9d65-b23c9aefdb34

**Comment by stanley355** [comment]
Duplicate issue: https://github.com/orgs/AyoEasy/projects/3/views/1?pane=issue&itemId=46740833

**Comment by stanley355** [comment]
The place of birth dropdown is only for passport
