### ISSUE TITLE
If the upload exceeds the avatar size limit of 5MB, an interception prompt needs to be raised.

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#141]
<img width="1120" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/72bc6e53-9ed8-4e4e-8f6b-cbdc97e2e9b5">

**Comment by stanley355** [comment]
@lavenderh is this happening on mobile app?

**Comment by lavenderh** [comment]
> @lavenderh is this happening on mobile app?

yes
