### ISSUE TITLE
Newly submitted orders are not displayed in the ongoing list of the activity page

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#152]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/92e67021-4a66-421c-84f4-286fe75d04d7

**Comment by dewi-pro** [comment]
answer is same like issue 153

**Comment by lavenderh** [comment]
> answer is same like issue 153

This issue needs to be revised
