### ISSUE TITLE
Orders requesting cancellation status are displayed in the ongoing list, and the list status is waiting for payment

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#153]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/1e69f673-34f2-4c2b-a277-8c725a262c1a

**Comment by dewi-pro** [comment]
the fetching from backend is taking long time in activity page

**Comment by lavenderh** [comment]
Why do you have to wait for a few minutes? Android does not have this problem. It does not refresh after clicking.
