### ISSUE TITLE
KYC-passport number rule error

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#17]
passport pattern is  "/^[A-Za-z0-9]{7,20}$/"

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/2c52d156-e46f-4b6c-879c-97a358b65674)

**Comment by stanley355** [comment]
@Vincenzo-Wang what's expected here?
