### ISSUE TITLE
Transaction status list error！

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#19]
status list data get from endpoint "common-config" ,   Get the transaction status list corresponding to this key "personal_transaction_status"

and  The data returned by this "common-config" endpoint  is some basic data used by the app. It can be requested once when the app is opened and cached locally.

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/c1305c13-6cff-4e67-95e4-65cf93f6dc18)

**Comment by stanley355** [comment]
@Vincenzo-Wang we just updated the test flight, please test again
