### ISSUE TITLE
Click Activity endpoint call error

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#20]
When I click the button, too many interfaces are called, and the parameters are passed incorrectly.

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/f24db010-6fda-48b2-8439-9a15371a35f6)

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/574dc66e-350a-4ef7-a861-a7cec2331514)

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/e5ecc900-41e2-443a-a0c5-fcf8ee7e9431)

**Comment by Vincenzo-Wang** [comment]
Clicking the activity button should only call the endpoint of the Ongoing state.

**Comment by Vincenzo-Wang** [comment]
When clicking on each transaction status under the history, request the report-list endpoint.

**Comment by Vincenzo-Wang** [comment]
If you have any questions, you can refer to the interface call of h5

**Comment by stanley355** [comment]
@Vincenzo-Wang 
1. `When clicking on each transaction status under the history, request the report-list endpoint.`
This is correct, we hit the backend endpoint every time the transaction status is changed, the web also do similar things
2. `missing parameter`
When did this happen? First time or when u click certain button?

**Comment by Vincenzo-Wang** [comment]
> @Vincenzo-Wang
> 
> 1. `When clicking on each transaction status under the history, request the report-list endpoint.`
>    This is correct, we hit the backend endpoint every time the transaction status is changed, the web also do similar things
> 2. `missing parameter`
>    When did this happen? First time or when u click certain button?

params  page_number and page_size  , page_number can't be null
