### ISSUE TITLE
Transaction details lack jump to transfer

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#22]
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/b69ebd6e-d0b2-4b5f-a88d-96c3dd6bf20d)
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/1ec4428b-aeab-4203-99be-bac9700c5cee)

When the transaction status is 0, there is an additional button at the bottom of the transaction details page. Click to jump to the process of selecting VA payment method.
If you don’t know the specific details, you can use the h5 process to experience it.

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/485c7dc0-a259-4de2-bd11-f8a1f90b3a77)
click this button to jump this follow page,and call these two endpoint
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/c3f53108-774f-4ba7-abd7-8cd0cded3797)

**Comment by stanley355** [comment]
@Vincenzo-Wang please tell us how to reproduce this
