### ISSUE TITLE
Home page, jump error for Ongoing Activity's Transfer

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#23]
When you click on the transaction list here, the page you jump to is consistent with the Activity’s Ongoing jump.

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/a8fc28a0-5862-4628-82af-e999e8f11dcc)

**Comment by stanley355** [comment]
@Vincenzo-Wang which is correct? the jump here or the jump in activity?

**Comment by Vincenzo-Wang** [comment]
the jump in activity is correct；
You can refer to the H5 process to take a look.
