### ISSUE TITLE
After the refund is rejected, click Resubmit. The process is wrong.

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#27]
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/038200b8-39d3-44c7-be39-e797ade7d6f8)

click this Resubmit button，should jump to this page,

**Comment by stanley355** [comment]
@Vincenzo-Wang jump to which page?

**Comment by Vincenzo-Wang** [comment]
Oh, sorry, my screenshot was not uploaded

**Comment by Vincenzo-Wang** [comment]
No, I uploaded it. Take a look and see why you didn’t see it.
https://github.com/AyoEasy/Easylink-Mobile-IOS/issues/28

**Comment by stanley355** [comment]
Oh it's duplicate, ok then
