### ISSUE TITLE
The add contact form has selected a date of birth and keeps prompting that you are under 18 years old, unable to add it normally

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#3]
When I choose this country，USD-Algeria,The add contact form has selected a date of birth and keeps prompting that you are under 18 years old, unable to add it normally
<img width="375" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/8ebeadcb-b597-4d5b-98b4-d268a6830962">

**Comment by rayhanmhd123** [comment]
fix build 46
