### ISSUE TITLE
The Recipient information field in the transaction details display error

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#34]
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/6a40bab7-fd41-463d-b858-c9864cae09e2)

should be this 

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/0e230106-1f68-40a4-978d-89b47503b29b)

**Comment by stanley355** [comment]
@Vincenzo-Wang please tell us how to reproduce it
