### ISSUE TITLE
The name used during registration is not verified by regularity.

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#35]
Name's pattern is '/^[a-zA-Z\.\s]{1,255}$/'

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/6745ad1b-5d84-4df6-aa1d-913fa5b863b7)

**Comment by stanley355** [comment]
@Vincenzo-Wang why should a name has pattern? Indonesian names sometime have number in their names

**Comment by rayhanmhd123** [comment]
@Vincenzo-Wang how about this bro?

**Comment by stanley355** [comment]
* Change `name` to `username`

**Comment by stanley355** [comment]
* Allow alphabet and number

**Comment by rayhanmhd123** [comment]
use this regex
user_name   ^[A-Za-z0-9]{20}$
