### ISSUE TITLE
Incomplete display of refund history list data

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#36]
**The interface returned three pieces of data, one for a failed refund and two for a successful refund. You only displayed the successful refunds, but not the failed refunds.**

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/067ab42a-5a78-4b25-a3a4-26cc371386aa)

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/8db4072c-a364-4864-ac9d-c00e5fad3631)

the end point return data :
`{
  "code": 0,
  "message": "",
  "data": {
    "total": "3",
    "refund_list": [
      {
        "refund_id": "92",
        "ref_id": "202311283000000000001417",
        "transfer_failed_date": "28-11-2023 16:09:44",
        "created_at": "30-11-2023 13:24:56",
        "status": "3",
        "corridor": "Austria",
        "status_display": "Declined",
        "amount_sent_display": "IDR 999,884",
        "destination_country": "AUT",
        "receipt_amount_display": "--"
      },
      {
        "refund_id": "77",
        "ref_id": "202311283000910000001382",
        "transfer_failed_date": "28-11-2023 13:42:18",
        "created_at": "28-11-2023 15:11:26",
        "status": "2",
        "corridor": "India",
        "status_display": "Refund Success",
        "amount_sent_display": "IDR 8,888,888",
        "destination_country": "IND",
        "receipt_amount_display": "IDR 8,888,000.00"
      },
      {
        "refund_id": "76",
        "ref_id": "202311273000000000001327",
        "transfer_failed_date": "27-11-2023 18:17:35",
        "created_at": "27-11-2023 18:27:35",
        "status": "2",
        "corridor": "Algeria",
        "status_display": "Refund Success",
        "amount_sent_display": "IDR 9,999,747",
        "destination_country": "DZA",
        "receipt_amount_display": "IDR 9,979,747.00"
      }
    ]
  }
}`

The correct display should be like this:
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/17b04bb5-9f4d-439e-b3ed-13e67a15de62)

**Comment by MN3280** [comment]
can you share the account for this issue? so that I can try at my device

**Comment by Vincenzo-Wang** [comment]
Version 53 still has problems，
1、It is recommended not to cache page data and get the latest data returned by the interface each time.
2、Don't request 16 pages of data just after entering the history page. It should be sliding loading.
