### ISSUE TITLE
When applying for passport Kyc, the form fields are incorrect and should be consistent with the design drawing.

### ISSUE THREAD

**Issue by Vincenzo-Wang** [AyoEasy/Easylink-Mobile-IOS#38]
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/1b58efc3-c4c9-4a2c-b11b-5f1d4a281739)

![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30740397/76ecd233-6701-46b3-8bd7-a34e518c7fe6)

**Comment by stanley355** [comment]
@Vincenzo-Wang which part is not consistent?
