### ISSUE TITLE
To grant credit with Chinese passport, every field in the app has been filled in. After clicking Submit, the credit cannot be granted successfully

### ISSUE THREAD

**Issue by Zhangxindong8** [AyoEasy/Easylink-Mobile-IOS#4]
<img width="340" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/55396891/190d87f5-2587-4bb9-a47e-783b0f4c482d">
There are videos in the Dingbing group, and github can't upload videos

**Comment by rayhanmhd123** [comment]
fix on build 46
