### ISSUE TITLE
When registering a phone number, the phone number filled in is only a number, but when submitting, an error message appears stating "phone_number : Phone number can only contain number."

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#40]
<img width="435" alt="F7D75F67-2090-4EFF-8BFF-7E5492410A39" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/ff0a91ef-e04c-4ddd-a1f5-c674549e7d7a">

**Comment by MN3280** [comment]
The error message you're encountering is from the backend. The phone numbers must begin with the number '8' in order to proceed with the registration.

**Comment by stanley355** [comment]
* Phone number should start 8 
* Length 7 - 16
* Will have regex for this
