### ISSUE TITLE
During the process of obtaining the SMS verification code on the password modification page, when clicking "forget the mail", there was no response or prompt

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#42]
<img width="437" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/91a9e622-8474-49bc-b225-6501f5975549">

**Comment by MN3280** [comment]
when clicking the forgot with email, it will back to the forgot password home.
What version of test flight are you? make sure it was updated , we're in 54 version right now
