### ISSUE TITLE
Inconsistency between copywriting and prototype drawings

### ISSUE THREAD

**Issue by jialiang1109** [AyoEasy/Easylink-Mobile-IOS#45]
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/35254102/23df853a-7adf-488f-97dc-ed525305a112)
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/35254102/cef3aa31-e256-4a28-80b9-ccaf01c0c3b2)

Prototype drawing
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/35254102/783ce3f3-a2a6-4828-ab0f-bcce1fd666cc)

**Comment by MN3280** [comment]
please confirm it to daisy first

**Comment by stanley355** [comment]
* Ask Tyo for the wording

**Comment by jialiang1109** [comment]
> * Ask Tyo for the wording

Just keep it consistent with the prototype diagram above

**Comment by stanley355** [comment]
@jialiang1109 I have discussed with Daisy about this, I'm gonna ask Tyo for the wording. That was just a note
