### ISSUE TITLE
When creating an account, when the password meets the rules and the comma is not treated as a special character, an error is reported when submitting, as shown below.

### ISSUE THREAD

**Issue by jialiang1109** [AyoEasy/Easylink-Mobile-IOS#50]
<img width="315" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/35254102/c03b8c2c-ff97-4617-852b-ff69953dec98">

**Comment by rayhanmhd123** [comment]
@Vincenzo-Wang i think in backend you not set , as a symbol right?

**Comment by stanley355** [comment]
* At least one of the symbol (.......)
* Will receive the symbol list

**Comment by jialiang1109** [comment]
Okay, ignore this question.
