### ISSUE TITLE
When creating an account, after submitting the information, you cannot click Submit when the verification code entered is incorrect, as shown below.

### ISSUE THREAD

**Issue by jialiang1109** [AyoEasy/Easylink-Mobile-IOS#51]
<img width="313" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/35254102/230ce07d-2a72-4624-a4e9-99c8dc7f8151">

**Comment by dewi-pro** [comment]
this in otp after creating account, in register page @jialiang1109 

![Image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/75671321/e8fd875f-fa16-44db-bd31-211b0767cee8)
