### ISSUE TITLE
The style of the pop-up window for adding contacts on the transfer page is inconsistent with the design drawing

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#55]
<img width="480" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/6c19df0a-4a4d-407e-b477-fd41120562be">
<img width="365" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/c8585c17-47ee-4669-a966-692fd5f25baf">

**Comment by stanley355** [comment]
* Show search only if there's recipient

**Comment by MN3280** [comment]
the search will only show if there's recipient , if no recipient it won't show

**Comment by wanghuijiao** [comment]
> the search will only show if there's recipient , if no recipient it won't show

OK
