### ISSUE TITLE
Send account information page, country field cannot be modified

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#58]
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/aa25c56b-2a3c-437a-bf23-a87f79879f78)

**Comment by stanley355** [comment]
* If the currency is USD or Euro, the recipient country can be different
* Send the country of the recipient to the backend

**Comment by wanghuijiao** [comment]
> * If the currency is USD or Euro, the recipient country can be different
> * Send the country of the recipient to the backend

I don't understand
