### ISSUE TITLE
Transfer details page, incomplete information display

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#62]
<img width="456" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/a4dbbf3b-1400-48f6-87a0-c0062d617360">

**Comment by stanley355** [comment]
![Image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/53996155/8eb00a8e-d6c3-43e5-99a9-6e15bd82fc77)

@wanghuijiao we hide the text if the text is too long

**Comment by wanghuijiao** [comment]
> ![Image](https://private-user-images.githubusercontent.com/53996155/288354888-8eb00a8e-d6c3-43e5-99a9-6e15bd82fc77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTUwNDYsIm5iZiI6MTcwMTg1NDc0NiwicGF0aCI6Ii81Mzk5NjE1NS8yODgzNTQ4ODgtOGViMDBhOGUtZDZjMy00M2U1LTk5YTktNmUxNWJkODJmYzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MjU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNTVjMThjNjM3Zjk0Yzk4ZWFkNDBjYWUxMzQyZGE3NDcxYzFmNGRjZWIzMzNmMjE5NzY1MzkwNGMzZjdkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wTkhWIPbCJvOFK3dy4cMwjiWJSrUWYyIrljHE5cQVu0)
> 
> @wanghuijiao we hide the text if the text is too long

OK
