### ISSUE TITLE
The app crashes and exits for some unknown reason, and has appeared three times so far

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#67]
![IMG_0833](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/88d64cd3-9500-4a11-bba6-654cc25ea047)

**Comment by stanley355** [comment]
What did you do before? Did you have any log?

**Comment by wanghuijiao** [comment]
> What did you do before? Did you have any log?

This does not have a stable scene appearing, it may not appear at any time, so it has appeared more than ten times so far
