### ISSUE TITLE
Orders with failed transactions should not be displayed in the ongoing list

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#68]
<img width="442" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/f9001de3-362c-4fe3-ae29-774c02619944">
<img width="469" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/2d339a8a-ac5c-4912-8f2e-e71d603c5c3a">

**Comment by dewi-pro** [comment]
so when failed i shouldnt be in history and ongoing?

**Comment by wanghuijiao** [comment]
> so when failed i shouldnt be in history and ongoing?

The transaction has already failed, it has already ended, not in progress
