### ISSUE TITLE
KYC credit blockage

### ISSUE THREAD

**Issue by lavenderh** [AyoEasy/Easylink-Mobile-IOS#7]
Kyc manually fills in the information, but the submission prompt indicates that there is an unfilled situation and the submission cannot be completed

https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/30519060/f28b96f7-5251-4a6f-bb5c-7bbc10822ef5

**Comment by rayhanmhd123** [comment]
fix on build 46
