### ISSUE TITLE
Clicking on the "Learn About These" button on the transfer page will result in an error on the redirected page

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#82]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/9c11c850-b4be-4c0b-8b70-bcfc11a0c153

<img width="431" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/e20cccc6-7283-4a75-a110-98f20f3dd6ed">

**Comment by MN3280** [comment]
will be build it today
