### ISSUE TITLE
The small tip on the right side of the home holiday information does not respond when clicked

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#86]
<img width="433" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/c1282ff8-b187-4c54-ac91-2143765bd355">

**Comment by MN3280** [comment]
Uploading RPReplay_Final1701845962.MP4…

**Comment by MN3280** [comment]
Uploading RPReplay_Final1701845962.MP4…

**Comment by MN3280** [comment]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/127370431/d1e05da6-12ce-4de7-a5b5-9c3f1bc5a722

**Comment by wanghuijiao** [comment]
> RPReplay_Final1701845962.MP4 
> I try it on test flight and it's responding

It can be folded in English, but not in Chinese
