### ISSUE TITLE
The three items in easypedia on the home page are not fully displayed, and a part of them is blocked below

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#87]
<img width="433" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/f82fcd2d-4051-4e39-b423-25a5f0f29778">
![image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/cead9a6d-a11a-461a-934e-dfe65df974f3)
design drawing
<img width="289" alt="image" src="https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/929e873b-b5ff-45e6-953b-92e39b9cab0e">

**Comment by stanley355** [comment]
![Image](https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/53996155/4cecb45b-d54d-4d5c-b8e0-d0b2c96f2cb6)

The three items is not fully displayed in figma
We will fix the part of the item is blocked
