### ISSUE TITLE
Click on the "Learn About These" button on the transmission page and an error message will appear on the page

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#93]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/08bc50c5-2dca-45e4-94ec-3688c49005e9

**Comment by MN3280** [comment]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/127370431/f97aa561-791b-4ab5-bbd5-ee6e1ebb0967


in our test flight, I didn't see any problem here. Did you still encountering this issue?

**Comment by rayhanmhd123** [comment]
it is oke by tester

**Comment by lavenderh** [comment]
pass
