### ISSUE TITLE
Changing password, clicking the save button did not respond

### ISSUE THREAD

**Issue by wanghuijiao** [AyoEasy/Easylink-Mobile-IOS#94]
https://github.com/AyoEasy/Easylink-Mobile-IOS/assets/152844804/2e1e3f9d-c48d-4c63-9ba3-87788bc93c9e

**Comment by MN3280** [comment]
what is the new password and confirm pass that you fill? there's still error message there, thats's why you can't proceed to the next page . please make sure that the password already match.
